yaml
services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: YTDL_NO_UPDATE
        value: true
    preDeployCommand: apt-get update && apt-get install -y ffmpeg